apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-process-deployment
  labels:
    app: evenprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evenprocessor
  template:
    metadata:
      labels:
        app: evenprocessor
    spec:
      containers:
      - name: evenprocessor
        image: ratheeshku/event-processor:V1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: event-process-service
spec:
  selector:
    app: evenprocessor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
